"""Engine de transpilação SAS → PySpark/Databricks.

Orquestra o pipeline: analyze → transpile por bloco → write output.
Suporta checkpointing via MigrationStateManager e flag --resume.

MVP Sprint 3: engine stub com checkpointing funcional.
A transpilação real (rule engine + LLM) será adicionada no Sprint 4.
"""

from __future__ import annotations

import logging
from pathlib import Path

from sas2dbx.models.migration_result import JobStatus, MigrationResult
from sas2dbx.models.sas_ast import SASFile
from sas2dbx.transpile.state import MigrationStateManager

logger = logging.getLogger(__name__)


class TranspilationEngine:
    """Orquestra a transpilação de um conjunto de jobs SAS.

    Args:
        output_dir: Diretório onde notebooks e state file serão gravados.
        resume: Se True, carrega estado anterior e pula jobs já concluídos.
    """

    def __init__(self, output_dir: Path, resume: bool = False) -> None:
        self._output_dir = output_dir
        self._resume = resume
        self._state = MigrationStateManager(output_dir)

    def run(self, sas_files: list[SASFile], execution_order: list[str]) -> list[MigrationResult]:
        """Executa a transpilação de todos os jobs na ordem fornecida.

        Falha em job N não interrompe jobs N+1..M.

        Args:
            sas_files: Lista de SASFiles a transpilar.
            execution_order: Ordem topológica de execução dos jobs.

        Returns:
            Lista de MigrationResult, um por job na execution_order.
        """
        file_map = {f.path.stem: f for f in sas_files}

        if self._resume:
            loaded = self._state.load()
            if not loaded:
                logger.warning(
                    "Engine: --resume solicitado mas state não encontrado — iniciando do zero"
                )
                self._state.init_fresh(execution_order)
        else:
            self._state.init_fresh(execution_order)

        jobs_to_run = self._state.get_pending_jobs(execution_order)

        logger.info(
            "Engine: %d job(s) para processar (de %d total)",
            len(jobs_to_run),
            len(execution_order),
        )

        results: list[MigrationResult] = []

        for job_id in execution_order:
            if job_id not in jobs_to_run:
                # Job já DONE — inclui resultado do state no output
                result = MigrationResult(
                    job_id=job_id,
                    status=JobStatus.DONE,
                    confidence=self._state.get_job_status(job_id) == JobStatus.DONE
                    and 1.0 or 0.0,
                )
                results.append(result)
                continue

            sas_file = file_map.get(job_id)
            if sas_file is None:
                logger.warning("Engine: job '%s' não encontrado em sas_files — pulando", job_id)
                continue

            self._state.mark_started(job_id)
            result = self._transpile_job(job_id, sas_file)
            results.append(result)

            if result.status == JobStatus.DONE:
                self._state.mark_done(job_id, result)
            else:
                self._state.mark_failed(job_id, result.error or "erro desconhecido")

        return results

    def _transpile_job(self, job_id: str, sas_file: SASFile) -> MigrationResult:
        """Transpila um único job SAS.

        MVP: stub que cria um placeholder de notebook.
        Sprint 4 substituirá por rule engine + LLM real.
        """
        try:
            output_path = self._output_dir / f"{job_id}.py"
            output_path.parent.mkdir(parents=True, exist_ok=True)

            # Sprint 4: substituir por transpilação real via rule engine + LLM
            placeholder = (
                f"# Databricks notebook source\n"
                f"# Generated by sas2dbx from {sas_file.path.name}\n"
                f"# TODO: transpilação real implementada no Sprint 4\n"
            )
            output_path.write_text(placeholder, encoding="utf-8")

            logger.info("Engine: job '%s' transpilado (stub) → %s", job_id, output_path)
            return MigrationResult(
                job_id=job_id,
                status=JobStatus.DONE,
                confidence=0.0,
                output_path=str(output_path),
            )
        except Exception as exc:
            logger.error("Engine: falha ao transpilar '%s': %s", job_id, exc)
            return MigrationResult(
                job_id=job_id,
                status=JobStatus.FAILED,
                error=str(exc),
            )
